
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
    - kubectl apply -f manifests/
  only:
    - main
