name: Apply Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Unzip changes
      run: |
        sudo apt-get install unzip
        unzip -o ph3ar-web-v1.0.7.zip -d ph3ar-web-release

    - name: Apply changes and commit
      run: |
        cd $GITHUB_WORKSPACE
        git add .
        git commit -m "Apply changes from apply_changes.zip"
        git push origin main || true

    - name: Handle conflicts and rebase
      if: failure()
      run: |
        git fetch origin
        git rebase origin/main
        git push origin main
      shell: /usr/bin/bash -e {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
