name: Apply Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Zip the current repository contents
      run: |
        sudo apt-get install zip
        zip -r repository.zip /home/runner/work/ph3ar-web/ph3ar-web

    - name: Unzip apply_changes.zip into the repository
      run: |
        sudo apt-get install unzip
        unzip -o apply_changes.zip -d /home/runner/work/ph3ar-web/ph3ar-web

    - name: Try to merge or push changes to main
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Apply changes from apply_changes.zip"
        git push origin main || exit 0
        git fetch origin
        git rebase origin/main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request if push to main fails
      if: failure()
      run: |
        git checkout -b apply-changes
        git push --set-upstream origin apply-changes
        gh pr create --title "Apply changes from apply_changes.zip" --body "This PR applies changes from apply_changes.zip."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
